


// export const NameOptions = [
//   { label: "   ", id: "", value: "" },
//   {
//     label: "SB Offers in Shop",
//     id: "SB Offers in Shop",
//     value: "SB Offers in Shop",
//   },
//   {
//     label: "Paid Placement (SB Offers)",
//     id: "Paid Placement (SB Offers)",
//     value: "Paid Placement (SB Offers)",
//   },
//   {
//     label: "Data Processing",
//     id: "Data Processing",
//     value: "Data Processing",
//   },
//   { label: "Programming", id: "Programming", value: "Programming" },
//   { label: "Sample", id: "Sample", value: "Sample" },
//   { label: "SB Offers", id: "SB Offers", value: "SB Offers" },
// ];

export const NameOptions = [
  { label: "   ", id: "", value: "" },
  {
    label: "Shopper Marketing",
    id: "Shopper Marketing",
    value: "Shopper Marketing",
  },
  {
    label: "Performance Marketing",
    id: "Performance Marketing",
    value: "Performance Marketing",
  },
  {
    label: "Performance Marketing Paid Placement",
    id: "Performance Marketing Paid Placement",
    value: "Performance Marketing Paid Placement",
  },
  { label: "Performance Marketing (tracked in aggregator)", id: "Performance Marketing (tracked in aggregator)", value: "Performance Marketing (tracked in aggregator)" },

];

export const VerticalOptions = [
  { label: "", id: "", value: "" },
  { label: "App Gaming", id: "1", value: "App Gaming" },
  {
    label: "Apparel & Accessories",
    id: "2",
    value: "Apparel & Accessories",
  },
  { label: "Automotive", id: "3", value: "Automotive" },
  { label: "Casino", id: "4", value: "Casino" },
  { label: "Charity", id: "5", value: "Charity" },
  { label: "Desktop Gaming", id: "6", value: "Desktop Gaming" },
  { label: "Education", id: "7", value: "Education" },
  { label: "Entertainment", id: "8", value: "Entertainment" },
  { label: "Finance", id: "9", value: "Finance" },
  { label: "Food & Drink", id: "10", value: "Food & Drink" },
  { label: "Gig Economy", id: "11", value: "Gig Economy" },
  { label: "H5/Browser", id: "12", value: "H5/Browser" },
  {
    label: "Health & Beauty",
    id: "13",
    value: "Health & Beauty",
  },
  { label: "Household", id: "14", value: "Household" },
  { label: "Kids & Family", id: "15", value: "Kids & Family" },
  {
    label: "Lead Gen/Panel Build",
    id: "16",
    value: "Lead Gen/Panel Build",
  },
  { label: "Pets", id: "17", value: "Pets" },
  {
    label: "Sports Gambling",
    id: "18",
    value: "Sports Gambling",
  },
  { label: "Technology", id: "19", value: "Technology" },
  { label: "Travel", id: "20", value: "Travel" },
];

export const RateTypeOptions = [
  { label: "   ", id: "", value: "" },
  { label: "CPA", id: "3", value: "CPA" },
  { label: "CPC", id: "1", value: "CPC" },
  { label: "CPI", id: "7", value: "CPI" },
  { label: "CPL", id: "5", value: "CPL" },
  { label: "CPM", id: "2", value: "CPM" },
  { label: "CPS", id: "9", value: "CPS" },
  { label: "CPV", id: "8", value: "CPV" },
  { label: "Rev Share", id: "4", value: "Rev Share" },
  { label: "Sponsorship", id: "6", value: "Sponsorship" },
];

export const DeptOptions = [
  { label: "   ", id: "", value: "" },
  { label: "Shop Roll-up", id: "23", value: "Shop Roll-up" },
  { label: "Discover Roll-up", id: "30", value: "Discover Roll-up" },
  { label: "Offerwalls", id: "31", value: "Offerwalls" },
  { label: "SB Offers", id: "32", value: "SB Offers" },
  { label: "Shopper Marketing", id: "45", value: "Shopper Marketing" },
  { label: "Shop", id: "34", value: "Shop" },
  { label: "Shop Other", id: "44", value: "Shop Other" },
  { label: "Dining", id: "54", value: "Dining" },
];

export const surveyLangOptions = [
  { label: "   ", id: "", value: "" },
  { label: "English", id: "1", value: "English" },
  { label: "Arabic", id: "2", value: "Arabic" },
  { label: "Chinese Mandarin", id: "3", value: "Chinese Mandarin" },
  { label: "Chinese Other", id: "4", value: "Chinese Other" },
  { label: "French", id: "5", value: "French" },
  { label: "German", id: "6", value: "German" },
  { label: "Hindi", id: "7", value: "Hindi" },
  { label: "Italian", id: "8", value: "Italian" },
  { label: "Japanese", id: "9", value: "Japanese" },
  { label: "Korean", id: "10", value: "Korean" },
  { label: "Spanish", id: "11", value: "Spanish" },
  { label: "Russian", id: "12", value: "Russian" },
  { label: "Vietnamese", id: "13", value: "Vietnamese" },
  { label: "Other", id: "14", value: "Other" },
];

export const ProdegeOptions = [
  { label: "", id: "", value: "" },
  { label: "Swagbucks", id: "1", value: "Swagbucks" },
  { label: "MyPoints", id: "2", value: "MyPoints" },
  { label: "ShopAtHome", id: "3", value: "ShopAtHome" },
  { label: "Swagbucks GmbH", id: "4", value: "Swagbucks GmbH" },
  { label: "InboxDollars", id: "6", value: "Inbox Dollars" },
  { label: "ySense", id: "8", value: "ySense" },
  { label: "CouponCause", id: "9", value: "CouponCause" },
  { label: "UPromise", id: "10", value: "UPromise" },
  { label: "Prodege", id: "11", value: "Prodege" },
  {
    label: "Prodege India Private Limited",
    id: "12",
    value: "Prodege India Private Limited",
  },
];

export const CountryOptions = [
  { label: "Afghanistan", id: "3", value: "Afghanistan" },
  { label: "Aland Islands", id: "247", value: "Aland Islands" },
  { label: "Albania", id: "6", value: "Albania" },
  { label: "Algeria", id: "62", value: "Algeria" },
  { label: "American Samoa", id: "12", value: "American Samoa" },
  { label: "Andorra", id: "1", value: "Andorra" },
  { label: "Angola", id: "9", value: "Angola" },
  { label: "Anguilla", id: "5", value: "Anguilla" },
  { label: "Antarctica", id: "10", value: "Antarctica" },
  { label: "Antigua and Barbuda", id: "4", value: "Antigua and Barbuda" },
  { label: "Argentina", id: "11", value: "Argentina" },
  { label: "Armenia", id: "7", value: "Armenia" },
  { label: "Aruba", id: "15", value: "Aruba" },
  { label: "Australia", id: "14", value: "Australia" },
  { label: "Austria", id: "13", value: "Austria" },
  { label: "Azerbaijan", id: "16", value: "Azerbaijan" },
  { label: "Bahamas", id: "31", value: "Bahamas" },
  { label: "Bahrain", id: "23", value: "Bahrain" },
  { label: "Bangladesh", id: "19", value: "Bangladesh" },
  { label: "Barbados", id: "18", value: "Barbados" },
  { label: "Belarus", id: "35", value: "Belarus" },
  { label: "Belgium", id: "20", value: "Belgium" },
  { label: "Belize", id: "36", value: "Belize" },
  { label: "Benin", id: "25", value: "Benin" },
  { label: "Bermuda", id: "27", value: "Bermuda" },
  { label: "Bhutan", id: "32", value: "Bhutan" },
  { label: "Bolivia", id: "29", value: "Bolivia" },
  {
    label: "Bonaire, Saint Eustatius, and Saba",
    id: "250",
    value: "Bonaire, Saint Eustatius, and Saba",
  },
  {
    label: "Bosnia and Herzegovina",
    id: "17",
    value: "Bosnia and Herzegovina",
  },
  { label: "Botswana", id: "34", value: "Botswana" },
  { label: "Bouvet Island", id: "33", value: "Bouvet Island" },
  { label: "Brazil", id: "30", value: "Brazil" },
  {
    label: "British Indian Ocean Territory",
    id: "106",
    value: "British Indian Ocean Territory",
  },
  { label: "Brunei Darrussalam", id: "28", value: "Brunei Darrussalam" },
  { label: "Bulgaria", id: "22", value: "Bulgaria" },
  { label: "Burkina Faso", id: "21", value: "Burkina Faso" },
  { label: "Burundi", id: "24", value: "Burundi" },
  { label: "Cambodia", id: "117", value: "Cambodia" },
  { label: "Cameroon", id: "46", value: "Cameroon" },
  { label: "Canada", id: "37", value: "Canada" },
  { label: "Canary Islands", id: "246", value: "Canary Islands" },
  { label: "Cape Verde", id: "53", value: "Cape Verde" },
  { label: "Cayman Islands", id: "124", value: "Cayman Islands" },
  {
    label: "Central African Republic",
    id: "40",
    value: "Central African Republic",
  },
  { label: "Ceuta and Melilla", id: "248", value: "Ceuta and Melilla" },
  { label: "Chad", id: "212", value: "Chad" },
  { label: "Chile", id: "45", value: "Chile" },
  { label: "China", id: "47", value: "China" },
  { label: "Christmas Island", id: "54", value: "Christmas Island" },
  {
    label: "Cocos (Keeling) Islands",
    id: "38",
    value: "Cocos (Keeling) Islands",
  },
  { label: "Colombia", id: "48", value: "Colombia" },
  { label: "Comoros", id: "119", value: "Comoros" },
  {
    label: "Congo, Democratic People's Republic",
    id: "39",
    value: "Congo, Democratic People's Republic",
  },
  { label: "Congo, Republic of", id: "41", value: "Congo, Republic of" },
  { label: "Cook Islands", id: "44", value: "Cook Islands" },
  { label: "Costa Rica", id: "49", value: "Costa Rica" },
  { label: "Cote d'Ivoire", id: "43", value: "Cote d'Ivoire" },
  { label: "Croatia/Hrvatska", id: "98", value: "Croatia/Hrvatska" },
  { label: "Cuba", id: "52", value: "Cuba" },
  { label: "Curacao", id: "251", value: "Curacao" },
  { label: "Cyprus", id: "55", value: "Cyprus" },
  { label: "Czech Republic", id: "56", value: "Czech Republic" },
  { label: "Denmark", id: "59", value: "Denmark" },
  { label: "Djibouti", id: "58", value: "Djibouti" },
  { label: "Dominica", id: "60", value: "Dominica" },
  { label: "Dominican Republic", id: "61", value: "Dominican Republic" },
  { label: "East Timor", id: "221", value: "East Timor" },
  { label: "Ecuador", id: "63", value: "Ecuador" },
  { label: "Egypt", id: "65", value: "Egypt" },
  { label: "El Salvador", id: "208", value: "El Salvador" },
  { label: "Equatorial Guinea", id: "88", value: "Equatorial Guinea" },
  { label: "Eritrea", id: "67", value: "Eritrea" },
  { label: "Estonia", id: "64", value: "Estonia" },
  { label: "Ethiopia", id: "69", value: "Ethiopia" },
  { label: "Falkland Islands", id: "72", value: "Falkland Islands" },
  { label: "Faroe Islands", id: "74", value: "Faroe Islands" },
  { label: "Fiji", id: "71", value: "Fiji" },
  { label: "Finland", id: "70", value: "Finland" },
  { label: "France", id: "75", value: "France" },
  { label: "French Guiana", id: "80", value: "French Guiana" },
  { label: "French Polynesia", id: "175", value: "French Polynesia" },
  {
    label: "French Southern Territories",
    id: "213",
    value: "French Southern Territories",
  },
  { label: "Gabon", id: "76", value: "Gabon" },
  { label: "Gambia", id: "85", value: "Gambia" },
  { label: "Georgia", id: "79", value: "Georgia" },
  { label: "Germany", id: "57", value: "Germany" },
  { label: "Ghana", id: "82", value: "Ghana" },
  { label: "Gibraltar", id: "83", value: "Gibraltar" },
  { label: "Greece", id: "89", value: "Greece" },
  { label: "Greenland", id: "84", value: "Greenland" },
  { label: "Grenada", id: "878", value: "Grenada" },
  { label: "Guadeloupe", id: "87", value: "Guadeloupe" },
  { label: "Guam", id: "92", value: "Guam" },
  { label: "Guatemala", id: "91", value: "Guatemala" },
  { label: "Guernsey", id: "81", value: "Guernsey" },
  { label: "Guinea", id: "86", value: "Guinea" },
  { label: "Guinea-Bissau", id: "93", value: "Guinea-Bissau" },
  { label: "Guyana", id: "94", value: "Guyana" },
  { label: "Haiti", id: "99", value: "Haiti" },
  {
    label: "Heard and McDonald Islands",
    id: "96",
    value: "Heard and McDonald Islands",
  },
  {
    label: "Holy See (City Vatican State)",
    id: "233",
    value: "Holy See (City Vatican State)",
  },
  { label: "Honduras", id: "97", value: "Honduras" },
  { label: "Hong Kong", id: "95", value: "Hong Kong" },
  { label: "Hungary", id: "100", value: "Hungary" },
  { label: "Iceland", id: "109", value: "Iceland" },
  { label: "India", id: "105", value: "India" },
  { label: "Indonesia", id: "101", value: "Indonesia" },
  {
    label: "Iran (Islamic Republic of)",
    id: "108",
    value: "Iran (Islamic Republic of)",
  },
  { label: "Iraq", id: "107", value: "Iraq" },
  { label: "Ireland", id: "102", value: "Ireland" },
  { label: "Isle of Man", id: "104", value: "Isle of Man" },
  { label: "Israel", id: "103", value: "Israel" },
  { label: "Italy", id: "110", value: "Italy" },
  { label: "Jamaica", id: "112", value: "Jamaica" },
  { label: "Japan", id: "114", value: "Japan" },
  { label: "Jersey", id: "111", value: "Jersey" },
  { label: "Jordan", id: "113", value: "Jordan" },
  { label: "Kazakhstan", id: "125", value: "Kazakhstan" },
  { label: "Kenya", id: "115", value: "Kenya" },
  { label: "Kiribati", id: "118", value: "Kiribati" },
  {
    label: "Korea, Democratic People's Republic",
    id: "121",
    value: "Korea, Democratic People's Republic",
  },
  { label: "Korea, Republic of", id: "122", value: "Korea, Republic of" },
  { label: "Kosovo", id: "254", value: "Kosovo" },
  { label: "Kuwait", id: "123", value: "Kuwait" },
  { label: "Kyrgyzstan", id: "116", value: "Kyrgyzstan" },
  {
    label: "Lao People's Democratic Republic",
    id: "126",
    value: "Lao People's Democratic Republic",
  },
  { label: "Latvia", id: "135", value: "Latvia" },
  { label: "Lebanon", id: "127", value: "Lebanon" },
  { label: "Lesotho", id: "132", value: "Lesotho" },
  { label: "Liberia", id: "131", value: "Liberia" },
  { label: "Libya", id: "136", value: "Libya" },
  { label: "Liechtenstein", id: "129", value: "Liechtenstein" },
  { label: "Lithuania", id: "133", value: "Lithuania" },
  { label: "Luxembourg", id: "134", value: "Luxembourg" },
  { label: "Macau", id: "148", value: "Macau" },
  { label: "Macedonia", id: "144", value: "Macedonia" },
  { label: "Madagascar", id: "142", value: "Madagascar" },
  { label: "Malawi", id: "156", value: "Malawi" },
  { label: "Malaysia", id: "158", value: "Malaysia" },
  { label: "Maldives", id: "155", value: "Maldives" },
  { label: "Mali", id: "145", value: "Mali" },
  { label: "Malta", id: "153", value: "Malta" },
  { label: "Marshall Islands", id: "143", value: "Marshall Islands" },
  { label: "Martinique", id: "150", value: "Martinique" },
  { label: "Mauritania", id: "151", value: "Mauritania" },
  { label: "Mauritius", id: "154", value: "Mauritius" },
  { label: "Mayotte", id: "342", value: "Mayotte" },
  { label: "Mexico", id: "157", value: "Mexico" },
  {
    label: "Micronesia, Federal State of",
    id: "73",
    value: "Micronesia, Federal State of",
  },
  { label: "Moldova, Republic of", id: "139", value: "Moldova, Republic of" },
  { label: "Monaco", id: "138", value: "Monaco" },
  { label: "Mongolia", id: "147", value: "Mongolia" },
  { label: "Montenegro", id: "140", value: "Montenegro" },
  { label: "Montserrat", id: "152", value: "Montserrat" },
  { label: "Morocco", id: "137", value: "Morocco" },
  { label: "Mozambique", id: "159", value: "Mozambique" },
  { label: "Myanmar", id: "146", value: "Myanmar" },
  { label: "Namibia", id: "160", value: "Namibia" },
  { label: "Nauru", id: "169", value: "Nauru" },
  { label: "Nepal", id: "168", value: "Nepal" },
  { label: "Netherlands", id: "166", value: "Netherlands" },
  { label: "New Caledonia", id: "161", value: "New Caledonia" },
  { label: "New Zealand", id: "171", value: "New Zealand" },
  { label: "Nicaragua", id: "165", value: "Nicaragua" },
  { label: "Niger", id: "162", value: "Niger" },
  { label: "Nigeria", id: "164", value: "Nigeria" },
  { label: "Niue", id: "170", value: "Niue" },
  { label: "Norfolk Island", id: "163", value: "Norfolk Island" },
  {
    label: "Northern Mariana Islands",
    id: "149",
    value: "Northern Mariana Islands",
  },
  { label: "Norway", id: "167", value: "Norway" },
  { label: "Oman", id: "172", value: "Oman" },
  { label: "Pakistan", id: "178", value: "Pakistan" },
  { label: "Palau", id: "185", value: "Palau" },
  { label: "Panama", id: "173", value: "Panama" },
  { label: "Papua New Guinea", id: "176", value: "Papua New Guinea" },
  { label: "Paraguay", id: "186", value: "Paraguay" },
  { label: "Peru", id: "174", value: "Peru" },
  { label: "Philippines", id: "177", value: "Philippines" },
  { label: "Pitcairn Island", id: "181", value: "Pitcairn Island" },
  { label: "Poland", id: "179", value: "Poland" },
  { label: "Portugal", id: "184", value: "Portugal" },
  { label: "Puerto Rico", id: "182", value: "Puerto Rico" },
  { label: "Qatar", id: "187", value: "Qatar" },
  { label: "Reunion Island", id: "188", value: "Reunion Island" },
  { label: "Romania", id: "189", value: "Romania" },
  { label: "Russian Federation", id: "190", value: "Russian Federation" },
  { label: "Rwanda", id: "191", value: "Rwanda" },
  { label: "Saint Barthélemy", id: "26", value: "Saint Barthélemy" },
  { label: "Saint Helena", id: "198", value: "Saint Helena" },
  {
    label: "Saint Kitts and Nevis",
    id: "120",
    value: "Saint Kitts and Nevis",
  },
  { label: "Saint Lucia", id: "128", value: "Saint Lucia" },
  { label: "Saint Martin", id: "141", value: "Saint Martin" },
  {
    label: "Saint Vincent and the Grenadines",
    id: "234",
    value: "Saint Vincent and the Grenadines",
  },
  { label: "Samoa", id: "241", value: "Samoa" },
  { label: "San Marino", id: "203", value: "San Marino" },
  {
    label: "Sao Tome and Principe",
    id: "207",
    value: "Sao Tome and Principe",
  },
  { label: "Saudi Arabia", id: "192", value: "Saudi Arabia" },
  { label: "Senegal", id: "204", value: "Senegal" },
  { label: "Serbia", id: "50", value: "Serbia" },
  { label: "Seychelles", id: "194", value: "Seychelles" },
  { label: "Sierra Leone", id: "202", value: "Sierra Leone" },
  { label: "Singapore", id: "197", value: "Singapore" },
  { label: "Sint Maarten", id: "252", value: "Sint Maarten" },
  { label: "Slovak Republic", id: "201", value: "Slovak Republic" },
  { label: "Slovenia", id: "199", value: "Slovenia" },
  { label: "Solomon Islands", id: "193", value: "Solomon Islands" },
  { label: "Somalia", id: "205", value: "Somalia" },
  { label: "South Africa", id: "244", value: "South Africa" },
  { label: "South Georgia", id: "90", value: "South Georgia" },
  { label: "South Sudan", id: "253", value: "South Sudan" },
  { label: "Spain", id: "68", value: "Spain" },
  { label: "Sri Lanka", id: "130", value: "Sri Lanka" },
  {
    label: "St. Pierre and Miquelon",
    id: "180",
    value: "St. Pierre and Miquelon",
  },
  { label: "State of Palestine", id: "183", value: "State of Palestine" },
  { label: "Sudan", id: "195", value: "Sudan" },
  { label: "Suriname", id: "206", value: "Suriname" },
  {
    label: "Svalbard and Jan Mayen Islands",
    id: "200",
    value: "Svalbard and Jan Mayen Islands",
  },
  { label: "Swaziland", id: "210", value: "Swaziland" },
  { label: "Sweden", id: "196", value: "Sweden" },
  { label: "Switzerland", id: "42", value: "Switzerland" },
  { label: "Syrian Arab Republic", id: "209", value: "Syrian Arab Republic" },
  { label: "Taiwan", id: "225", value: "Taiwan" },
  { label: "Tajikistan", id: "216", value: "Tajikistan" },
  { label: "Tanzania", id: "226", value: "Tanzania" },
  { label: "Thailand", id: "215", value: "Thailand" },
  { label: "Togo", id: "214", value: "Togo" },
  { label: "Tokelau", id: "217", value: "Tokelau" },
  { label: "Tonga", id: "220", value: "Tonga" },
  { label: "Trinidad and Tobago", id: "223", value: "Trinidad and Tobago" },
  { label: "Tunisia", id: "219", value: "Tunisia" },
  { label: "Turkey", id: "222", value: "Turkey" },
  { label: "Turkmenistan", id: "218", value: "Turkmenistan" },
  {
    label: "Turks and Caicos Islands",
    id: "211",
    value: "Turks and Caicos Islands",
  },
  { label: "Tuvalu", id: "224", value: "Tuvalu" },
  { label: "Uganda", id: "228", value: "Uganda" },
  { label: "Ukraine", id: "227", value: "Ukraine" },
  { label: "United Arab Emirates", id: "2", value: "United Arab Emirates" },
  { label: "United Kingdom", id: "77", value: "United Kingdom" },
  { label: "United States", id: "230", value: "United States" },
  { label: "Uruguay", id: "231", value: "Uruguay" },
  {
    label: "US Minor Outlying Islands",
    id: "229",
    value: "US Minor Outlying Islands",
  },
  { label: "Uzbekistan", id: "232", value: "Uzbekistan" },
  { label: "Vanuatu", id: "239", value: "Vanuatu" },
  { label: "Venezuela", id: "235", value: "Venezuela" },
  { label: "Vietnam", id: "238", value: "Vietnam" },
  {
    label: "Virgin Islands (British)",
    id: "236",
    value: "Virgin Islands (British)",
  },
  { label: "Virgin Islands (USA)", id: "237", value: "Virgin Islands (USA)" },
  {
    label: "Wallis and Futuna Islands",
    id: "240",
    value: "Wallis and Futuna Islands",
  },
  { label: "Western Sahara", id: "66", value: "Western Sahara" },
  { label: "Yemen", id: "242", value: "Yemen" },
  { label: "Zambia", id: "245", value: "Zambia" },
  { label: "Zimbabwe", id: "246", value: "Zimbabwe" },
];

export const StatusOptions = [
  { label: "", id: "", value: "" },
  { label: "Postponed (due to COVID-19)", id: "1", value: "Postponed (due to COVID-19)" },
  { label: "Postponed (other reasons)", id: "2", value: "Postponed (other reasons)" },
  { label: "Canceled (due to COVID-19)", id: "3", value: "Canceled (due to COVID-19)" },
  { label: "Canceled (other reasons)", id: "4", value: "Canceled (other reasons)" },
  { label: "Paid for with Pollfish Credits", id: "5", value: "Paid for with Pollfish Credits" }
]

export const System1PricingOptions = [
  { label: "", id: "", value: "" },
  { label: "Rate Card", id: "1", value: "Rate Card" },
  { label: "Custom Pricing", id: "2", value: "Custom Pricing" }
]